services:
  - type: web
    name: json-converter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=1 --threads=4 --timeout=60
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    plan: free
